#define DROPBEAR_DEFPORT "2222"
#define DSS_PRIV_FILENAME "/opt/dropbear/etc/dropbear_dss_host_key"
#define RSA_PRIV_FILENAME "/opt/dropbear/etc/dropbear_rsa_host_key"
#define ECDSA_PRIV_FILENAME "/opt/dropbear/etc/dropbear_ecdsa_host_key"
#define DROPBEAR_SMALL_CODE 0
#define DROPBEAR_BLOWFISH 1
#define DROPBEAR_SVR_PASSWORD_AUTH 1
#define DROPBEAR_SVR_PAM_AUTH 0
#define DROPBEAR_SVR_PUBKEY_AUTH 1
#define DROPBEAR_PATH_SSH_PROGRAM "/opt/dropbear/current/bin/dbclient"
#define LOG_COMMANDS 1
#define DEFAULT_KEEPALIVE 30
#define DEFAULT_PATH "/usr/local/bin:/usr/bin:/bin:/opt/dropbear/current/bin"
